### ISSUE TITLE
Input stream not null

### ISSUE THREAD

**Issue by essentialexch** [PaulHigin/PSThreadJob#25] opened 2018-10-03 17:57 UTC
Thanks for this utility. Was recommended by Steve Lee and it works well. More examples would be helpful. :-)

However, I've run into an issue. Start-ThreadJob provides an open input stream to each ThreadJob (separate from the cmdlet input stream). Is there any way to call CloseInputStream for the Threadjobs?

I ran into this:

> When invoked using BeginInvoke, invocation doesn't
> finish until Input is closed. Caller of BeginInvoke must
> close the input buffer after all input has been written to
> input buffer. Input buffer is closed by calling
> Close() method.
> 
> If you want this command to execute as a standalone cmdlet
> (that is, using command-line parameters only),
> be sure to call Close() before calling BeginInvoke().  Otherwise,
> the command will be executed as though it had external input.
> If you observe that the command isn't doing anything,
> this may be the reason.

As described here: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.begininvoke?view=powershellsdk-1.1.0

I am NOT a developer. Would this be as simple to fix as adding a _input.Complete() before line 762? Or is there another way?

**Comment by PaulHigin** [comment] 2018-10-03 22:49
I don't understand the issue.  Why do you want to close the input stream?  Please provide repro steps including expected and actual behavior.

**Comment by essentialexch** [comment] 2018-10-05 17:41
I am attempting to use PSThreadJob to deploy Upgrade Readiness to several thousand workstations. The relevant script is described here: https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script

Below, $array contains the list of computerNames that are available for deployment.

This leads to:

`0..$($array.count - 1) |% { Start-ThreadJob -Name $array[$_] -ThrottleLimit 10 -ArgumentList $array[ $_ ] -ScriptBlock { Param( $cn ); cmd /c "start /wait /min c:\Scripts\pilot\PsExec.exe \\$cn -accepteula -w c:\scripts\AzureUA -h -s c:\scripts\AzureUA\RunConfig.bat >nul <nul" } }
`

This line in RunConfig.bat hangs waiting on user input in every thread:

`for /f %%i in ('Powershell.exe $pshome') do set PowershellHome=%%I
`

A simple enter/carriage return is enough. But I think if input was closed it wouldn't hang.

This does NOT occur when running the script interactively. RunConfig.bat does not hang.

I don't want to hit enter thousands of times.

So, I had two thoughts: [1] is there a way to call CloseInputStream on the object returned from get-job, or [2] would _input.Complete() before line 762 be equivalent?

I'm welcome to other ideas.

**Comment by essentialexch** [comment] 2018-10-05 17:46
Oh yeah - the "start /wait /min" and adding "<nul >nul" at the end of psexec.exe were methods I was using to attempt to work around my issue. They neither helped nor hurt, so are simply cruft at this point and I will remove them.

**Comment by PaulHigin** [comment] 2018-10-09 21:51
Sorry for the late reply, I have just now found time to get back to this.  What you describe above is not due to the job input stream ... that is only used for input piped to the Start-ThreadJob cmdlet.  

Instead it sounds like the RunConfig.bat file is prompting the user for confirmation, and it is probably doing this via stdIn/stdOut.  Since thread jobs run in the current process, the prompt would go to the console host and is probably why you need to hit Enter to continue.

You can take a look at RunConfig.bat and figure out where/why this prompt is occurring.  Usually scripts or batch files have a way to run without user input.  Sometimes they have a -Force command line switch, or you can include "/y" or something on the command line.  Something like:
```
RunConfig.bat /y
or
RunConfig.bat /f
```

**Comment by essentialexch** [comment] 2018-10-09 22:17
No sir. With all due respect, you are incorrect. The batch script is not prompting for confirmation. You obviously did not look at the script even though I provided a link to it.

As I wrote above, the problem does not occur when the script is executed interactively.

The problem also does not occur when I deploy the script using SCCM or Group Policy. Also as described in the link I provided.

I told you the specific line in the script that was hanging. I've verified this repeatedly.

This is an issue with PSThreadJob.

If you could, please answer the first question I asked. If you don't, I'll spend the necessary hours to try to figure out how install VS Studio Community.  [1] is there a way to call CloseInputStream on the object returned from get-job, or [2] would _input.Complete() before line 762 be equivalent?

**Comment by SeeminglyScience** [comment] 2018-10-10 00:00
@swngdnz The problem is most likely `psexec` , it has some strange interactions with PowerShell.   [Here's a SO](https://stackoverflow.com/questions/1786185/run-powershell-scripts-on-remote-pc) detailing a bunch of work arounds, with different work arounds working for different folks.  I've ran into that a lot in the past. It works in some circumstances, others you need to hit enter to do anything.  I'd recommend trying to work in `Invoke-Command` instead if possible.

Also "input" in this case is referring to pipeline input.  For example in the case of `1, 2 | ForEach-Object { $_ }`, the `1, 2` is sent as pipeline input to `ForEach-Object`.  The terminology is a little misleading in that regard.  If you ran into the issue described in the documentation, pressing enter wouldn't help it, only killing the process would.

**Comment by PaulHigin** [comment] 2018-10-11 15:26
Thanks @SeeminglyScience, it does sound like psexec is causing the interruption.  As with many "hangs" attributed to PowerShell, in most cases the hang is due to the script being run ... usually during an API call or running a native command.  I don't believe this is an issue of the job hanging but a hang in what the job is running.  So I am going to close this issue.  Feel free to re-open if new information comes to light.

**Closed as completed by PaulHigin** 2018-10-11 15:26 UTC
